---
- yum: name={{item}} state=present
  with_items:
    - upsilon-node
    - upsilon-web
    - upsilon-custodian
    - upsilon-reactor
    - elinks
    - mariadb-server
- service: name={{item}} state=started enabled=yes
  with_items: 
    - httpd
    - mariadb

